version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = [
    "vue",
    "react"
  ]
  style_guide = "standard"
  dialect = "typescript"
